name: Build and Upload Slam‑MirrorBot EXE

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name for release (e.g. v1.0.0)'
        required: true
  release:
    types: [published]

jobs:
  build-windows-exe:
    runs-on: windows-latest
    name: Build Slam Mirror Bot EXE for Windows

    steps:
      - name: 🛎️ Checkout current (dummy) repo
        uses: actions/checkout@v3

      - name: 📥 Clone Slam Repo
        run: |
          git clone https://github.com/juniorsundrashu/slam.git bot_src

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 🔧 Install dependencies
        run: |
          cd bot_src
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt || echo "⚠️ Missing wheels ignored"
          pip uninstall -y uvloop xattr || echo "✅ Unneeded deps removed"

      - name: 🧠 Create launcher.py (entry point)
        run: |
          cd bot_src
          echo "from bot import LOGGER, bot_loop" > launcher.py
          echo "" >> launcher.py
          echo "if __name__ == '__main__':" >> launcher.py
          echo "    LOGGER.info('Starting Slam Mirror Bot...')" >> launcher.py
          echo "    bot_loop()" >> launcher.py

      - name: 🛠️ Build EXE using PyInstaller with full requirements
        run: |
          cd bot_src

          # Extract all module names from requirements.txt
          $reqs = Get-Content requirements.txt | ForEach-Object {
            if ($_ -match '^\s*([^=><\[\s]+)') { $matches[1] }
          }

          # Build hidden-import arguments
          $hiddenArgs = $reqs | ForEach-Object { "--hidden-import=$_" } -join " "

          # Optional: collect submodules from common dynamic imports
          $collectArgs = "--collect-submodules pyrogram --collect-submodules urllib3"

          # Build EXE
          pyinstaller --onefile launcher.py --name slam_mirror_bot --distpath dist `
            --add-data "source.zip;." `
            $hiddenArgs $collectArgs

      - name: 📦 Zip the executable
        run: |
          powershell Compress-Archive -Path bot_src\dist\slam_mirror_bot.exe -DestinationPath slam_mirror_bot_win.zip

      - name: 🚀 Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.event.release.tag_name }}
          files: slam_mirror_bot_win.zip
        env:
          GITHUB_TOKEN: ${{ secrets.HUB_TOKEN }}
